using System;
using System.Collections.Generic;
using System.Text;
namespace SafetyMonitorExtension
{
    /// <summary>
    /// Represents a safety-related event, including its condition, type, source, message, and the UTC time it occurred.
    /// </summary>
    public class SafetyEvent
    {
		/// <summary>
		/// The name of the application, device, or driver that generated the event.
		/// </summary>
		/// <exception cref="ASCOM.InvalidValueException">Thrown if Source is null or an empty string.</exception>
		public string Source { get; set; }

        /// <summary>
        /// A short name for what is being monitored e.g. "Mains Supply Voltage", "12V Regulated Voltage", "Perimeter Alarm", "Wind Speed".
        /// </summary>
        /// <exception cref="ASCOM.InvalidValueException">Thrown if Name is null or an empty string.</exception>
        /// <remarks>
        /// Each name must have an associated unique <see cref="Id"/> to allow disambiguation from events generated by other sources.
        /// </remarks>
        public string Name { get; set; }

		/// <summary>
		/// A unique ID that identifies the event that triggered this safety condition.
		/// </summary>
		/// <exception cref="ASCOM.InvalidValueException">Thrown if Id is null or an empty string.</exception>
		/// <remarks>
		/// <para>
		/// This field enables client applications to update an existing event or remove it from the list provided by <see cref="ISafetyMonitorV4.SafetyEvents">ISafetyMonitorV4.SafetyEvents</see> .
		/// </para>
		/// <para>
		/// Safety monitors that implement this method must ensure that their update mechanic enforces Id as a unique key. This is to ensure that an existing record in the safety monitor's list will be updated if, 
        /// for example, the source provides a revised event description e.g. a change to a monitored value but the condition remains unsafe.
		/// </para>
		/// <para>
		/// Values should be chosen to minimise the chance of replicating IDs used by other sources. A GUID is recommended.
		/// </para>
		/// </remarks>
		public string Id { get; set; }

        /// <summary>
        /// The type of safety event that occurred.
        /// </summary>
        public SafetyEventType Type { get; set; }

        /// <summary>
        /// The condition that triggered the safety event.
        /// </summary>
        public SafetyEventTrigger Trigger { get; set; }

		/// <summary>
		/// A description of the event and why it was triggered.
		/// </summary>
		/// <exception cref="ASCOM.InvalidValueException">Thrown if Description is null or an empty string.</exception>
		public string Description { get; set; }

        /// <summary>
        /// The UTC time at which the event occurred.
        /// </summary>
        /// <remarks>
        /// Should default to DateTime.UtcNow.
        /// </remarks>
        public DateTime EventTimeUtc { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Initializes a new instance of the SafetyEvent class with the specified source, name, ID, trigger, type, description and time.
        /// </summary>
        /// <param name="source">The component that generated the event.</param>
        /// <param name="name">A short name for the rule that triggered this event.</param>
        /// <param name="id">A unique ID, defined by the event source, to identify the rule that triggered this event. See <see cref="Id"/> for more details.</param>
        /// <param name="type">The type of safety event.</param>
        /// <param name="trigger">The condition that triggered the safety event.</param>
        /// <param name="description">A description providing additional context about the safety event.</param>
        /// <remarks>The EventTimeUtc property should be automatically set to the current UTC time when the event is created.</remarks>
        public SafetyEvent(string source, string name, string id, SafetyEventType type, SafetyEventTrigger trigger, string description)
        {
            if(string.IsNullOrEmpty(source)) throw new ArgumentNullException(nameof(source));
            if(string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
            if(string.IsNullOrEmpty(id)) throw new ArgumentNullException(nameof(id));
            if(string.IsNullOrEmpty(description)) throw new ArgumentNullException(nameof(description));

            Source = source;
            Name = name;
            Id = id;
            Type = type;
            Trigger = trigger;
            Description = description;
            EventTimeUtc = DateTime.UtcNow;
        }
    }
}
