namespace ObsMan
{
    public class State
    {
        static uint serverTransactionId = 0;
        public State() { }

        public int TopOfVisibleLog { get; set; } = 0;

        public int LastNumberOfLogLines { get; set; } = 0;

        public string ApplicationLog { get; set; } = $"{Globals.WELCOME_MESSAGE}\r\n";

        public uint GetServerTransactionId()
        {
            serverTransactionId++;
            return serverTransactionId;
        }

        #region Test values

        //private readonly string testLogMessage = "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" + "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n" +
        //    "Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log. Start of Application log.\r\n"
        //    ;

        #endregion
    }
}
