namespace Sentinel
{
    public enum PropertyName
    {
        CloudCover,
        DewPoint,
        Humidity,
        Pressure,
        RainRate,
        SkyBrightness,
        SkyQuality,
        SkyTemperature,
        StarFWHM,
        Temperature,
        WindDirection,
        WindGust,
        WindSpeed,
        SafetyMonitor0,
        SafetyMonitor1,
        SafetyMonitor2,
        SafetyMonitor3,
        SafetyMonitor4,
        SafetyMonitor5,
        SafetyMonitor6,
        SafetyMonitor7,
        SafetyMonitor8,
        SafetyMonitor9
    }
}
